services:
  react:
    container_name: f1_react
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "9999:3000"
    volumes:
      - ./react:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    networks:
      - f1_network

  apigateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    container_name: f1_apigateway
    ports:
      - "9010:5041"
    environment:
      - ASPNETCORE_URLS=http://+:5041
      - DOTNET_DataProtection__KeyDirectory=/var/protection-keys
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=your_secret_key
      - Jwt__Issuer=your_issuer
      - Jwt__Audience=your_audience
      - ConnectionStrings__DefaultConnection=Server=db;Database=my_database;User=root;Password=your_password;
      - Redis__Connection=redis:6379
    depends_on:
      - mysql
      - redis
    networks:
      - f1_network


  scraper:
    container_name: f1_scraper
    build:
      context: ./scraper
      dockerfile: Dockerfile
    ports:
      - "9020:8000"
    volumes:
      - ./scraper:/app
    depends_on:
      - postgres
      - redis
    networks:
      - f1_network

  postgres:
    image: postgres:14
    container_name: f1_postgres
    hostname: f1_postgres
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    env_file:
      - ./envs/.env.postgres
    networks:
      - f1_network
    ports:
      - "9040:5432"
    restart: "always"

  mysql:
    image: mysql:latest
    container_name: f1_mysql
    hostname: f1_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword123$"
      MYSQL_DATABASE: users
      TZ: UTC
    command: --default-time-zone=UTC
    networks:
      - f1_network
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "9041:3306"
    restart: "always"

  redis:
    image: redis:6.2-alpine
    container_name: f1_redis
    hostname: f1_redis
    ports:
      - "9050:6379"
    networks:
      - f1_network
    restart: "always"

networks:
  f1_network:
    name: f1_network
    driver: bridge

volumes:
  mysql_data:
    name: f1_mysql_data
    driver: local